//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpencesRecordClient.ExpencesRecordService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExpencesRecordService.ExpencesRecordServiceSoap")]
    public interface ExpencesRecordServiceSoap {
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addCategory", ReplyAction="*")]
        ExpencesRecordClient.ExpencesRecordService.addCategoryResponse addCategory(ExpencesRecordClient.ExpencesRecordService.addCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<ExpencesRecordClient.ExpencesRecordService.addCategoryResponse> addCategoryAsync(ExpencesRecordClient.ExpencesRecordService.addCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addExpences", ReplyAction="*")]
        ExpencesRecordClient.ExpencesRecordService.addExpencesResponse addExpences(ExpencesRecordClient.ExpencesRecordService.addExpencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addExpences", ReplyAction="*")]
        System.Threading.Tasks.Task<ExpencesRecordClient.ExpencesRecordService.addExpencesResponse> addExpencesAsync(ExpencesRecordClient.ExpencesRecordService.addExpencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeExpences", ReplyAction="*")]
        bool removeExpences(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeExpences", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> removeExpencesAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCategory", Namespace="http://tempuri.org/", Order=0)]
        public ExpencesRecordClient.ExpencesRecordService.addCategoryRequestBody Body;
        
        public addCategoryRequest() {
        }
        
        public addCategoryRequest(ExpencesRecordClient.ExpencesRecordService.addCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public addCategoryRequestBody() {
        }
        
        public addCategoryRequestBody(int id, string type) {
            this.id = id;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExpencesRecordClient.ExpencesRecordService.addCategoryResponseBody Body;
        
        public addCategoryResponse() {
        }
        
        public addCategoryResponse(ExpencesRecordClient.ExpencesRecordService.addCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addCategoryResult;
        
        public addCategoryResponseBody() {
        }
        
        public addCategoryResponseBody(bool addCategoryResult) {
            this.addCategoryResult = addCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addExpencesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addExpences", Namespace="http://tempuri.org/", Order=0)]
        public ExpencesRecordClient.ExpencesRecordService.addExpencesRequestBody Body;
        
        public addExpencesRequest() {
        }
        
        public addExpencesRequest(ExpencesRecordClient.ExpencesRecordService.addExpencesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addExpencesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string des;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int eid;
        
        public addExpencesRequestBody() {
        }
        
        public addExpencesRequestBody(string type, string des, float amount, System.DateTime date, int eid) {
            this.type = type;
            this.des = des;
            this.amount = amount;
            this.date = date;
            this.eid = eid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addExpencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addExpencesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExpencesRecordClient.ExpencesRecordService.addExpencesResponseBody Body;
        
        public addExpencesResponse() {
        }
        
        public addExpencesResponse(ExpencesRecordClient.ExpencesRecordService.addExpencesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addExpencesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addExpencesResult;
        
        public addExpencesResponseBody() {
        }
        
        public addExpencesResponseBody(bool addExpencesResult) {
            this.addExpencesResult = addExpencesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExpencesRecordServiceSoapChannel : ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpencesRecordServiceSoapClient : System.ServiceModel.ClientBase<ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap>, ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap {
        
        public ExpencesRecordServiceSoapClient() {
        }
        
        public ExpencesRecordServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpencesRecordServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpencesRecordServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpencesRecordServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExpencesRecordClient.ExpencesRecordService.addCategoryResponse ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap.addCategory(ExpencesRecordClient.ExpencesRecordService.addCategoryRequest request) {
            return base.Channel.addCategory(request);
        }
        
        public bool addCategory(int id, string type) {
            ExpencesRecordClient.ExpencesRecordService.addCategoryRequest inValue = new ExpencesRecordClient.ExpencesRecordService.addCategoryRequest();
            inValue.Body = new ExpencesRecordClient.ExpencesRecordService.addCategoryRequestBody();
            inValue.Body.id = id;
            inValue.Body.type = type;
            ExpencesRecordClient.ExpencesRecordService.addCategoryResponse retVal = ((ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap)(this)).addCategory(inValue);
            return retVal.Body.addCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExpencesRecordClient.ExpencesRecordService.addCategoryResponse> ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap.addCategoryAsync(ExpencesRecordClient.ExpencesRecordService.addCategoryRequest request) {
            return base.Channel.addCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExpencesRecordClient.ExpencesRecordService.addCategoryResponse> addCategoryAsync(int id, string type) {
            ExpencesRecordClient.ExpencesRecordService.addCategoryRequest inValue = new ExpencesRecordClient.ExpencesRecordService.addCategoryRequest();
            inValue.Body = new ExpencesRecordClient.ExpencesRecordService.addCategoryRequestBody();
            inValue.Body.id = id;
            inValue.Body.type = type;
            return ((ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap)(this)).addCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExpencesRecordClient.ExpencesRecordService.addExpencesResponse ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap.addExpences(ExpencesRecordClient.ExpencesRecordService.addExpencesRequest request) {
            return base.Channel.addExpences(request);
        }
        
        public bool addExpences(string type, string des, float amount, System.DateTime date, int eid) {
            ExpencesRecordClient.ExpencesRecordService.addExpencesRequest inValue = new ExpencesRecordClient.ExpencesRecordService.addExpencesRequest();
            inValue.Body = new ExpencesRecordClient.ExpencesRecordService.addExpencesRequestBody();
            inValue.Body.type = type;
            inValue.Body.des = des;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            inValue.Body.eid = eid;
            ExpencesRecordClient.ExpencesRecordService.addExpencesResponse retVal = ((ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap)(this)).addExpences(inValue);
            return retVal.Body.addExpencesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExpencesRecordClient.ExpencesRecordService.addExpencesResponse> ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap.addExpencesAsync(ExpencesRecordClient.ExpencesRecordService.addExpencesRequest request) {
            return base.Channel.addExpencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExpencesRecordClient.ExpencesRecordService.addExpencesResponse> addExpencesAsync(string type, string des, float amount, System.DateTime date, int eid) {
            ExpencesRecordClient.ExpencesRecordService.addExpencesRequest inValue = new ExpencesRecordClient.ExpencesRecordService.addExpencesRequest();
            inValue.Body = new ExpencesRecordClient.ExpencesRecordService.addExpencesRequestBody();
            inValue.Body.type = type;
            inValue.Body.des = des;
            inValue.Body.amount = amount;
            inValue.Body.date = date;
            inValue.Body.eid = eid;
            return ((ExpencesRecordClient.ExpencesRecordService.ExpencesRecordServiceSoap)(this)).addExpencesAsync(inValue);
        }
        
        public bool removeExpences(int id) {
            return base.Channel.removeExpences(id);
        }
        
        public System.Threading.Tasks.Task<bool> removeExpencesAsync(int id) {
            return base.Channel.removeExpencesAsync(id);
        }
    }
}
